import { Pet, PlaceLocation, SocialPost, ParkMeetup, Product, RewardCoupon, Mission, UserRewards, VetMessage } from './types';

export const INITIAL_PETS: Pet[] = [
  {
    id: 'pet-1',
    name: 'Thor',
    breed: 'Golden Retriever',
    ageYears: 3,
    ageMonths: 4,
    birthDate: '2023-04-10',
    gender: 'male',
    neutered: true,
    avatar: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=600&q=80',
    weightKg: 32.5,
    weightHistory: [
      { date: '2025-08-10', weightKg: 30.2 },
      { date: '2025-11-15', weightKg: 31.4 },
      { date: '2026-02-20', weightKg: 32.0 },
      { date: '2026-05-18', weightKg: 32.2 },
      { date: '2026-08-10', weightKg: 32.5 },
    ],
    microchipId: '981020000349812',
    bloodType: 'DEA 1.1 Positivo',
    pedigree: 'CBKC 2023/049182',
    emergencyContact: {
      ownerName: 'Lucas Ferreira & Camila',
      phone: '(11) 98765-4321',
      secondaryPhone: '(11) 97654-3210',
      primaryVetName: 'Dra. Mariana Prado (CRMV-SP 38491)',
      primaryVetPhone: '(11) 91234-5678',
      clinic24h: 'Hospital Veterinário VetCare 24h',
      clinic24hPhone: '(11) 3456-7890',
      clinic24hAddress: 'Av. Rebouças, 1420 - Pinheiros, São Paulo - SP',
    },
    allergies: [
      {
        id: 'alg-1',
        name: 'Sensibilidade a Frango (Dermatite atópica alimentar)',
        severity: 'moderate',
        type: 'food',
        treatment: 'Dieta hipoalergênica com salmão e cordeiro',
      },
      {
        id: 'alg-2',
        name: 'Dipirona Sódica (Hipersensibilidade moderada)',
        severity: 'severe',
        type: 'medication',
        treatment: 'Substituir por Meloxicam ou Tramadol sob prescrição',
      },
    ],
    chronicConditions: ['Tendência a displasia coxofemoral (grau leve - prevenção com condroprotetor)'],
    continuousMedications: ['Condroton Plus 1000mg (1 comprimido a cada 24h no café da manhã)'],
    vaccines: [
      {
        id: 'vac-1',
        name: 'V10 Polivalente Canina (Nobivac)',
        type: 'essential',
        dateAdministered: '2025-09-12',
        nextDueDate: '2026-09-12',
        status: 'due_soon',
        administeredBy: 'Dra. Mariana Prado',
        batchNumber: 'NVB-88390',
        clinic: 'Clínica VetCare Pinheiros',
        notes: 'Dose anual de reforço obrigatória',
      },
      {
        id: 'vac-2',
        name: 'Antirrábica Canina (Defensor)',
        type: 'essential',
        dateAdministered: '2025-10-05',
        nextDueDate: '2026-10-05',
        status: 'up_to_date',
        administeredBy: 'Dr. Rodrigo Menezes',
        batchNumber: 'DEF-44120',
        clinic: 'Centro de Controle de Zoonoses / VetCare',
        notes: 'Excelente imunidade',
      },
      {
        id: 'vac-3',
        name: 'Gripe Canina / Tosse dos Canis (Bronchi-Shield)',
        type: 'recommended',
        dateAdministered: '2025-08-20',
        nextDueDate: '2026-08-20',
        status: 'overdue',
        administeredBy: 'Dra. Mariana Prado',
        batchNumber: 'BRN-1092',
        clinic: 'Clínica VetCare Pinheiros',
        notes: 'Necessário para frequentar creches e parques!',
      },
      {
        id: 'vac-4',
        name: 'Giardíase Canina (GiardiaVax)',
        type: 'recommended',
        dateAdministered: '2025-11-10',
        nextDueDate: '2026-11-10',
        status: 'up_to_date',
        administeredBy: 'Dra. Mariana Prado',
        batchNumber: 'GVX-3091',
        clinic: 'Clínica VetCare Pinheiros',
      },
      {
        id: 'vac-5',
        name: 'Leishmaniose Canina (Leish-Tec)',
        type: 'optional',
        dateAdministered: '2026-01-15',
        nextDueDate: '2027-01-15',
        status: 'up_to_date',
        administeredBy: 'Dr. Roberto Lemos',
        batchNumber: 'LTC-7721',
        clinic: 'Hospital Vet 24h',
      },
    ],
    dewormingHistory: [
      {
        id: 'dew-1',
        productName: 'Bravecto 20-40kg (Comprimido Mastigável)',
        type: 'flea_tick',
        dateAdministered: '2026-06-01',
        nextDueDate: '2026-09-01',
        frequencyMonths: 3,
        weightAtTime: 32.1,
        status: 'due_soon',
        notes: 'Proteção trimestral contra carrapatos e pulgas',
      },
      {
        id: 'dew-2',
        productName: 'Drontal Plus Sabor Carne (35kg)',
        type: 'dewormer',
        dateAdministered: '2026-04-10',
        nextDueDate: '2026-08-10',
        frequencyMonths: 4,
        weightAtTime: 32.0,
        status: 'overdue',
        notes: 'Vermifugação intestinal periódica recomendada',
      },
    ],
    consultations: [
      {
        id: 'cons-1',
        date: '2026-06-20',
        veterinarian: 'Dra. Mariana Prado',
        clinic: 'Clínica VetCare Pinheiros',
        reason: 'Check-up semestral e avaliação articular das patas traseiras',
        diagnosis: 'Ótimo estado geral, articulação preservada sem dor ao toque',
        prescriptions: ['Manter Condroton Plus 1000mg', 'Evitar pisos excessivamente lisos em corrida'],
        cost: 220.0,
        followUpDate: '2026-12-20',
        notes: 'Pelagem brilhante, peso estável e dentes sem tártaro avançado.',
      },
      {
        id: 'cons-2',
        date: '2026-02-14',
        veterinarian: 'Dr. Marcelo Viana (Dermatologista)',
        clinic: 'DermatoVet Especialidades',
        reason: 'Coceira na pata esquerda e lambedura frequente',
        diagnosis: 'Dermatite por contato com grama molhada / alérgeno leve',
        prescriptions: ['Shampoo Clorexiderm a cada 3 dias', 'Spray anti-séptico tópico'],
        cost: 310.0,
        notes: 'Quadro 100% resolvido em 7 dias.',
      },
    ],
    exams: [
      {
        id: 'ex-1',
        date: '2026-06-20',
        title: 'Hemograma Completo + Bioquímico Renal e Hepático',
        category: 'blood',
        laboratory: 'LabVet Diagnósticos Premium',
        resultsSummary: 'Hemácias, leucócitos e plaquetas normais. Creatinina: 1.1 mg/dL, ALT/TGP: 38 U/L (perfeitos).',
        status: 'normal',
        fileName: 'Hemograma_Thor_Jun2026.pdf',
      },
      {
        id: 'ex-2',
        date: '2025-11-15',
        title: 'Raio-X Digital Coxofemoral (Controle de Displasia)',
        category: 'xray',
        laboratory: 'Centro Radiológico Vet Image',
        resultsSummary: 'Sem sinais de osteoartrose severa. Ângulo de Norberg dentro da média esperada para a raça.',
        status: 'normal',
        fileName: 'RaioX_Bacia_Thor_Nov2025.pdf',
      },
      {
        id: 'ex-3',
        date: '2025-08-10',
        title: 'Ultrassonografia Abdominal Total',
        category: 'ultrasound',
        laboratory: 'Hospital VetCare 24h',
        resultsSummary: 'Órgãos abdominais com dimensões e ecotextura preservadas. Bexiga sem cálculos.',
        status: 'normal',
        fileName: 'Ultrassom_Thor_Ago2025.pdf',
      },
    ],
  },
  {
    id: 'pet-2',
    name: 'Mel',
    breed: 'Vira-lata (SRD Caramelo)',
    ageYears: 2,
    ageMonths: 1,
    birthDate: '2024-07-02',
    gender: 'female',
    neutered: true,
    avatar: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=600&q=80',
    weightKg: 14.8,
    weightHistory: [
      { date: '2025-10-01', weightKg: 13.5 },
      { date: '2026-02-15', weightKg: 14.2 },
      { date: '2026-07-20', weightKg: 14.8 },
    ],
    microchipId: '981020000782190',
    bloodType: 'DEA 1.1 Negativo (Doadora Universal)',
    emergencyContact: {
      ownerName: 'Lucas Ferreira',
      phone: '(11) 98765-4321',
      primaryVetName: 'Dr. André Camargo (CRMV-SP 41203)',
      primaryVetPhone: '(11) 98112-9900',
      clinic24h: 'Hospital Veterinário VetCare 24h',
      clinic24hPhone: '(11) 3456-7890',
      clinic24hAddress: 'Av. Rebouças, 1420 - Pinheiros, São Paulo - SP',
    },
    allergies: [],
    chronicConditions: [],
    continuousMedications: [],
    vaccines: [
      {
        id: 'vac-m1',
        name: 'V10 Polivalente Canina',
        type: 'essential',
        dateAdministered: '2026-01-20',
        nextDueDate: '2027-01-20',
        status: 'up_to_date',
        administeredBy: 'Dr. André Camargo',
        batchNumber: 'V10-9921',
        clinic: 'Pet Pop Saúde',
      },
      {
        id: 'vac-m2',
        name: 'Antirrábica Canina',
        type: 'essential',
        dateAdministered: '2026-01-20',
        nextDueDate: '2027-01-20',
        status: 'up_to_date',
        administeredBy: 'Dr. André Camargo',
        batchNumber: 'RAB-8812',
        clinic: 'Pet Pop Saúde',
      },
    ],
    dewormingHistory: [
      {
        id: 'dew-m1',
        productName: 'Simparic 10-20kg',
        type: 'flea_tick',
        dateAdministered: '2026-07-25',
        nextDueDate: '2026-08-25',
        frequencyMonths: 1,
        status: 'due_soon',
      },
    ],
    consultations: [],
    exams: [],
  },
];

export const MOCK_PLACES: PlaceLocation[] = [
  {
    id: 'plc-1',
    name: 'Petz Mega Store & Centro Veterinário',
    type: 'petshop',
    categoryTitle: 'Pet Shop & Farmácia Veterinária',
    address: 'Av. Brigadeiro Faria Lima, 2100',
    neighborhood: 'Jardim Paulistano',
    city: 'São Paulo - SP',
    distanceKm: 0.8,
    rating: 4.8,
    reviewCount: 420,
    isOpenNow: true,
    openHours: '08:00 às 22:00 (Seg a Dom)',
    phone: '(11) 3030-9900',
    whatsapp: '11930309900',
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=600&q=80',
    tags: ['Banho & Tosa', 'Farmácia Pet', 'Estacionamento Grátis', 'Rações Premium'],
    services: ['Banho com ozonioterapia', 'Tosa na tesoura', 'Farmácia 24h', 'Delivery express em 2h'],
    latitude: -23.5702,
    longitude: -46.6890,
  },
  {
    id: 'plc-2',
    name: 'Hospital Veterinário VetCare 24 Horas',
    type: 'vet24h',
    categoryTitle: 'Hospital e UTI Veterinária 24h',
    address: 'Av. Rebouças, 1420',
    neighborhood: 'Pinheiros',
    city: 'São Paulo - SP',
    distanceKm: 1.2,
    rating: 4.9,
    reviewCount: 680,
    isOpenNow: true,
    openHours: 'Aberto 24 Horas (Plantão Emergencial)',
    phone: '(11) 3456-7890',
    whatsapp: '11934567890',
    image: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=600&q=80',
    tags: ['Emergência 24h', 'UTI Canina', 'Cirurgia Geral', 'Raio-X & Ultrassom'],
    services: ['Pronto-socorro 24h', 'Banco de Sangue Canino', 'Especialidades Médicas', 'Internação com câmeras'],
    latitude: -23.5630,
    longitude: -46.6820,
  },
  {
    id: 'plc-3',
    name: 'Bruno Adestramento & Comportamento Canino',
    type: 'trainer',
    categoryTitle: 'Adestrador Profissional Certificado',
    address: 'Atendimento Domiciliar e no Parque Ibirapuera',
    neighborhood: 'Moema / Vila Mariana',
    city: 'São Paulo - SP',
    distanceKm: 2.1,
    rating: 5.0,
    reviewCount: 142,
    isOpenNow: true,
    openHours: '07:00 às 19:00 (Seg a Sáb)',
    phone: '(11) 97722-3344',
    whatsapp: '11977223344',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=600&q=80',
    tags: ['Adestramento Positivo', 'Reatividade & Agressividade', 'Filhotes', 'Passeio Educativo'],
    trainerDetails: {
      specialties: ['Obediência Básica e Avançada', 'Controle de Ansiedade de Separação', 'Socialização em Parques', 'Xixi no Lugar Certo'],
      experienceYears: 8,
      hourlyRate: 140.0,
      certifications: ['Certificado CPDT-KA', 'Especialista em Adestramento Positivo sem Punição', 'Membro da Associação Brasileira de Comportamento Canino'],
      bio: 'Mais de 8 anos transformando a convivência entre tutores e cães através do reforço positivo e comunicação canina clara.',
    },
    latitude: -23.5850,
    longitude: -46.6600,
  },
  {
    id: 'plc-4',
    name: 'Camila Santos - Dog Trainer & Psicologia Canina',
    type: 'trainer',
    categoryTitle: 'Adestradora & Comportamentalista',
    address: 'Atendimento Domiciliar - Zona Sul e Oeste',
    neighborhood: 'Pinheiros / Perdizes',
    city: 'São Paulo - SP',
    distanceKm: 1.5,
    rating: 4.9,
    reviewCount: 96,
    isOpenNow: true,
    openHours: '08:00 às 18:00',
    phone: '(11) 98833-2211',
    whatsapp: '11988332211',
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=600&q=80',
    tags: ['Filhotes', 'Adestramento para Apartamento', 'Cães Reativos', 'Guia Solta'],
    trainerDetails: {
      specialties: ['Adaptação de filhotes', 'Latidos excessivos', 'Passeio calmo sem puxar a guia', 'Socialização de cães resgatados'],
      experienceYears: 6,
      hourlyRate: 130.0,
      certifications: ['Graduada em Medicina Veterinária com foco em Etologia', 'Adestramento Cognitivo'],
      bio: 'Foco no bem-estar animal e harmonia na rotina do lar. Aulas práticas com a família inteira.',
    },
    latitude: -23.5600,
    longitude: -46.6950,
  },
  {
    id: 'plc-5',
    name: 'Parque Ibirapuera (Parcão Portão 6)',
    type: 'dogpark',
    categoryTitle: 'Parque Pet Friendly & Área Cercada',
    address: 'Av. Pedro Álvares Cabral - Portão 6',
    neighborhood: 'Vila Mariana',
    city: 'São Paulo - SP',
    distanceKm: 2.8,
    rating: 4.9,
    reviewCount: 1200,
    isOpenNow: true,
    openHours: '05:00 às 23:00 (Aberto todos os dias)',
    phone: '(11) 5574-5045',
    image: 'https://images.unsplash.com/photo-1534361960057-19889db9621e?auto=format&fit=crop&w=600&q=80',
    tags: ['Área 100% Cercada', 'Bebedouros Caninos', 'Grama Ampla', 'Iluminação Noturna', 'Sombra e Árvores'],
    services: ['Pista de Agility amadora', 'Bebedouro exclusivo para pets', 'Lixeiras com saquinhos cata-caca'],
    latitude: -23.5874,
    longitude: -46.6576,
  },
  {
    id: 'plc-6',
    name: 'Cobasi & Espaço Vet Integrado',
    type: 'petshop',
    categoryTitle: 'Mega Pet Shop & Centro Estético',
    address: 'Rua Teodoro Sampaio, 1850',
    neighborhood: 'Pinheiros',
    city: 'São Paulo - SP',
    distanceKm: 1.4,
    rating: 4.7,
    reviewCount: 310,
    isOpenNow: true,
    openHours: '08:00 às 21:30',
    phone: '(11) 3814-2200',
    whatsapp: '11938142200',
    image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=600&q=80',
    tags: ['Acessórios', 'Farmácia', 'Rações Super Premium', 'Pet Care'],
    services: ['Banho higiênico', 'Hidratação de pelagem com argan', 'Venda de medicamentos sob receita'],
    latitude: -23.5590,
    longitude: -46.6870,
  },
];

export const MOCK_SOCIAL_POSTS: SocialPost[] = [
  {
    id: 'post-1',
    authorPet: {
      name: 'Thor',
      breed: 'Golden Retriever',
      avatar: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=300&q=80',
      ownerName: 'Lucas Ferreira',
    },
    locationName: 'Parque Ibirapuera - Parcão',
    timestamp: 'Há 45 minutos',
    imageUrl: 'https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?auto=format&fit=crop&w=800&q=80',
    caption: 'Manhã de sol e muita correria com a bolinha no Parcão! Quem mais vai estar por aqui hoje à tarde para o piquenique canino? 🐾🎾',
    likes: 38,
    hasLiked: true,
    commentsCount: 4,
    comments: [
      {
        id: 'c-1',
        author: 'Camila & Luna',
        petName: 'Luna',
        avatar: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=150&q=80',
        text: 'A Luna vai por volta das 16h! Vamos nos encontrar perto das árvores!',
        timestamp: 'Há 30 min',
      },
      {
        id: 'c-2',
        author: 'Rodrigo & Fred',
        petName: 'Fred (Beagle)',
        avatar: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&w=150&q=80',
        text: 'Que foto linda! Thor é super veloz kkkk',
        timestamp: 'Há 15 min',
      },
    ],
    tag: 'parque',
  },
  {
    id: 'post-2',
    authorPet: {
      name: 'Barthô',
      breed: 'Bulldog Francês',
      avatar: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=300&q=80',
      ownerName: 'Mariana Souza',
    },
    locationName: 'Praça Vilaboim - Higienópolis',
    timestamp: 'Há 3 horas',
    imageUrl: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=800&q=80',
    caption: 'Primeiro dia de passeio depois de completar todas as vacinas da infância! Todo pomposo com a bandana nova que comprei no marketplace da AuAu Care!',
    likes: 54,
    hasLiked: false,
    commentsCount: 6,
    comments: [
      {
        id: 'c-3',
        author: 'Felipe & Duke',
        petName: 'Duke',
        avatar: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=150&q=80',
        text: 'Parabéns Barthô! Agora o mundo é seu pra cheirar tudo!',
        timestamp: 'Há 2 horas',
      },
    ],
    tag: 'conquista',
  },
  {
    id: 'post-3',
    authorPet: {
      name: 'Zoe & Theo',
      breed: 'Border Collie',
      avatar: 'https://images.unsplash.com/photo-1503256207526-0d5d80fa2f47?auto=format&fit=crop&w=300&q=80',
      ownerName: 'Gabriel Lima',
    },
    locationName: 'Parque Villa-Lobos',
    timestamp: 'Ontem',
    imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=800&q=80',
    caption: 'Treino de Frisbee de hoje com o adestrador Bruno. Border Collie com energia gasta é tutor feliz em casa!',
    likes: 89,
    hasLiked: true,
    commentsCount: 8,
    comments: [],
    tag: 'socializacao',
  },
];

export const MOCK_PARK_MEETUPS: ParkMeetup[] = [
  {
    id: 'meet-1',
    title: 'Encontro Oficial de Goldens & Cães Dóceis',
    parkName: 'Parque Ibirapuera (Portão 6 - Gramado Principal)',
    address: 'Av. Pedro Álvares Cabral, Portão 6',
    city: 'São Paulo - SP',
    date: 'Sábado, 29 de Agosto',
    time: '15:30 às 18:00',
    organizer: {
      name: 'Lucas Ferreira',
      petName: 'Thor',
      avatar: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=200&q=80',
    },
    targetBreedOrSize: 'Cães Médios e Grandes (Todas as raças e SRD bem-vindos)',
    description: 'Tragam água, bolinhas, petiscos e toalha para quem quiser sentar na grama! Faremos sorteio de brindes da AuAu Care.',
    participants: [
      {
        id: 'p-1',
        ownerName: 'Lucas Ferreira',
        petName: 'Thor',
        petBreed: 'Golden Retriever',
        avatar: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=150&q=80',
      },
      {
        id: 'p-2',
        ownerName: 'Camila & Luna',
        petName: 'Luna',
        petBreed: 'Golden Retriever',
        avatar: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=150&q=80',
      },
      {
        id: 'p-3',
        ownerName: 'Marcos Paulo',
        petName: 'Pipoca',
        petBreed: 'Labrador',
        avatar: 'https://images.unsplash.com/photo-1591769225440-811ad7d6eab2?auto=format&fit=crop&w=150&q=80',
      },
      {
        id: 'p-4',
        ownerName: 'Juliana Dias',
        petName: 'Toby',
        petBreed: 'SRD Caramelo',
        avatar: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=150&q=80',
      },
    ],
    maxParticipants: 20,
    isJoined: true,
    status: 'upcoming',
  },
  {
    id: 'meet-2',
    title: 'Socialização Matinal de Filhotes (Até 10 meses)',
    parkName: 'Parque Villa-Lobos (Parcão Canino)',
    address: 'Av. Prof. Fonseca Rodrigues, 2001',
    city: 'São Paulo - SP',
    date: 'Domingo, 30 de Agosto',
    time: '09:00 às 11:00',
    organizer: {
      name: 'Adestradora Camila Santos',
      petName: 'Maya',
      avatar: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=200&q=80',
    },
    targetBreedOrSize: 'Filhotes vacinados de todos os portes',
    description: 'Encontro supervisionado com dicas gratuitas de dessensibilização e brincadeiras saudáveis sem estresse.',
    participants: [
      {
        id: 'p-5',
        ownerName: 'Camila Santos',
        petName: 'Maya',
        petBreed: 'Border Collie',
        avatar: 'https://images.unsplash.com/photo-1503256207526-0d5d80fa2f47?auto=format&fit=crop&w=150&q=80',
      },
      {
        id: 'p-6',
        ownerName: 'Beatriz Ramos',
        petName: 'Nico',
        petBreed: 'Spitz Alemão',
        avatar: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=150&q=80',
      },
    ],
    maxParticipants: 12,
    isJoined: false,
    status: 'upcoming',
  },
  {
    id: 'meet-3',
    title: 'Encontro dos Cães de Focinho Achatado (Braquicefálicos)',
    parkName: 'Parque do Povo (Gramado Leste)',
    address: 'Av. Henrique Chamma, 420 - Itaim Bibi',
    city: 'São Paulo - SP',
    date: 'Quarta, 02 de Setembro',
    time: '17:00 às 18:30',
    organizer: {
      name: 'Mariana Souza',
      petName: 'Barthô',
      avatar: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=200&q=80',
    },
    targetBreedOrSize: 'Bulldog Francês, Pug, Boston Terrier, Shih-tzu',
    description: 'Horário fresquinho no fim de tarde para evitar hipertermia. Tragam tapete gelado e muita água gelada!',
    participants: [
      {
        id: 'p-7',
        ownerName: 'Mariana Souza',
        petName: 'Barthô',
        petBreed: 'Bulldog Francês',
        avatar: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=150&q=80',
      },
    ],
    maxParticipants: 15,
    isJoined: false,
    status: 'upcoming',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Ração Royal Canin Maxi Adult (15kg)',
    brand: 'Royal Canin',
    category: 'racao',
    price: 349.90,
    originalPrice: 389.90,
    rating: 4.9,
    reviewsCount: 312,
    image: 'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?auto=format&fit=crop&w=600&q=80',
    description: 'Alimento completo super premium para cães adultos de raças grandes (de 26 a 44 kg). Suporte à saúde osteoarticular e alta digestibilidade.',
    dogSizeTarget: 'large',
    inStock: true,
    pointsEarned: 350,
    isBestSeller: true,
    badge: 'Mais Vendido',
  },
  {
    id: 'prod-2',
    name: 'Ração Premier Formula Adultos Raças Médias Frango (12kg)',
    brand: 'Premier Pet',
    category: 'racao',
    price: 269.90,
    originalPrice: 299.90,
    rating: 4.8,
    reviewsCount: 180,
    image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=600&q=80',
    description: 'Ração super premium rica em proteínas nobres, ômegas 3 e 6, e hexametafosfato de sódio para prevenção de tártaro.',
    dogSizeTarget: 'medium',
    inStock: true,
    pointsEarned: 270,
    isBestSeller: true,
  },
  {
    id: 'prod-3',
    name: 'Antipulgas e Carrapatos Bravecto 20 a 40kg',
    brand: 'MSD Saúde Animal',
    category: 'farmacia',
    price: 249.90,
    originalPrice: 275.00,
    rating: 5.0,
    reviewsCount: 540,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
    description: '1 comprimido mastigável com 12 semanas (3 meses) completas de proteção contínua contra carrapatos e pulgas. Eliminação rápida.',
    dogSizeTarget: 'large',
    inStock: true,
    pointsEarned: 250,
    badge: 'Indispensável',
  },
  {
    id: 'prod-4',
    name: 'Brinquedo KONG Classic Vermelho Grande (L)',
    brand: 'KONG',
    category: 'brinquedos',
    price: 119.90,
    originalPrice: 139.90,
    rating: 4.9,
    reviewsCount: 420,
    image: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&w=600&q=80',
    description: 'Borracha natural super resistente e saltitante. Ideal para rechear com ração úmida, frutas ou petiscos congelados para enriquecimento ambiental.',
    dogSizeTarget: 'all',
    inStock: true,
    pointsEarned: 120,
    badge: 'Top Enriquecimento',
  },
  {
    id: 'prod-5',
    name: 'Petisco Natural Orelha Bovina Desidratada (Pacote c/ 5 un)',
    brand: 'Pure Natural Pets',
    category: 'petiscos',
    price: 38.90,
    rating: 4.9,
    reviewsCount: 195,
    image: 'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?auto=format&fit=crop&w=600&q=80',
    description: '100% natural, sem conservantes, aromatizantes ou químicos. Promove limpeza mecânica dos dentes e alívio do estresse.',
    dogSizeTarget: 'all',
    inStock: true,
    pointsEarned: 40,
  },
  {
    id: 'prod-6',
    name: 'Cama Ortopédica Memory Foam Impermeável Lavável (G)',
    brand: 'AuAu Sleep',
    category: 'acessorios',
    price: 289.00,
    originalPrice: 340.00,
    rating: 4.8,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?auto=format&fit=crop&w=600&q=80',
    description: 'Espuma viscoelástica de alta densidade que alivia a pressão nas articulações. Capa impermeável removível para máquina.',
    dogSizeTarget: 'large',
    inStock: true,
    pointsEarned: 290,
    badge: 'Conforto VIP',
  },
  {
    id: 'prod-7',
    name: 'Suplemento Articular Condroton Plus 1000mg (60 comp)',
    brand: 'Vetnil',
    category: 'farmacia',
    price: 184.90,
    rating: 4.9,
    reviewsCount: 152,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
    description: 'Sulfato de Condroitina e Glucosamina para regeneração e manutenção de cartilagens em cães de médio e grande porte.',
    dogSizeTarget: 'all',
    inStock: true,
    pointsEarned: 185,
  },
  {
    id: 'prod-8',
    name: 'Bolinha Ultra Squeaker Chuckit! Flutuante (Tamanho M - 2un)',
    brand: 'Chuckit!',
    category: 'brinquedos',
    price: 74.90,
    rating: 5.0,
    reviewsCount: 260,
    image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=600&q=80',
    description: 'Borracha de alta durabilidade com apito protegido, não machuca os dentes e pula muito alto no parque.',
    dogSizeTarget: 'all',
    inStock: true,
    pointsEarned: 75,
  },
];

export const MOCK_REWARD_COUPONS: RewardCoupon[] = [
  {
    id: 'coup-1',
    title: 'R$ 35 de Desconto em Rações Super Premium',
    discountDescription: 'Válido para compras acima de R$ 150 no Marketplace AuAu',
    pointsCost: 400,
    category: 'shop',
    code: 'AUAU35RACAO',
    expiresInDays: 30,
  },
  {
    id: 'coup-2',
    title: 'Banho Completo com Hidratação Grátis',
    discountDescription: 'Em qualquer Pet Shop parceiro da rede credenciada',
    pointsCost: 750,
    category: 'bath',
    code: 'BANHOVIPFREE',
    expiresInDays: 45,
  },
  {
    id: 'coup-3',
    title: '50% OFF em 1ª Sessão de Adestramento',
    discountDescription: 'Com qualquer adestrador certificado do aplicativo',
    pointsCost: 500,
    category: 'trainer',
    code: 'ADESTRA50',
    expiresInDays: 60,
  },
  {
    id: 'coup-4',
    title: 'Consulta Veterinária de Rotina Gratuita',
    discountDescription: 'Avaliação clínica semestral em clínicas conveniadas',
    pointsCost: 1200,
    category: 'vet',
    code: 'CONSULTA0800',
    expiresInDays: 90,
  },
];

export const MOCK_MISSIONS: Mission[] = [
  {
    id: 'mis-1',
    title: 'Cadastrar Histórico de Vacinação do Cão',
    description: 'Mantenha o prontuário atualizado com a última V10 ou Antirrábica',
    points: 150,
    category: 'health',
    isCompleted: true,
    actionKey: 'add_vaccine',
  },
  {
    id: 'mis-2',
    title: 'Confirmar Presença em um Encontro no Parque',
    description: 'Socialize seu pet participando de um evento da comunidade',
    points: 100,
    category: 'social',
    isCompleted: true,
    actionKey: 'join_meetup',
  },
  {
    id: 'mis-3',
    title: 'Verificar Ficha de Emergência SOS',
    description: 'Confira se os contatos de emergência e alergias estão corretos',
    points: 80,
    category: 'health',
    isCompleted: false,
    actionKey: 'open_sos',
  },
  {
    id: 'mis-4',
    title: 'Realizar uma Compra no Marketplace',
    description: 'Garanta petiscos ou ração e ganhe pontos em dobro',
    points: 200,
    category: 'shop',
    isCompleted: false,
    actionKey: 'make_purchase',
  },
  {
    id: 'mis-5',
    title: 'Avaliar um Pet Shop ou Adestrador no Mapa',
    description: 'Ajude outros tutores compartilhando sua experiência',
    points: 90,
    category: 'daily',
    isCompleted: false,
    actionKey: 'review_place',
  },
];

export const INITIAL_USER_REWARDS: UserRewards = {
  pointsBalance: 680,
  totalPointsEarned: 1450,
  tier: 'Ouro',
  tierProgress: 72,
  redeemedCoupons: [
    {
      couponId: 'coup-1',
      code: 'AUAU35RACAO',
      title: 'R$ 35 de Desconto em Rações Super Premium',
      redeemedAt: '18/08/2026',
    },
  ],
  completedMissions: ['mis-1', 'mis-2'],
  streakDays: 14,
};

export const INITIAL_VET_MESSAGES: VetMessage[] = [
  {
    id: 'msg-sys-1',
    sender: 'system',
    text: '🩺 Plantão Veterinário 24h AuAu Care iniciado. Todos os nossos médicos veterinários possuem registro ativo no CRMV. Em caso de emergências com risco de vida (intoxicação grave, convulsões contínuas, atropelamento), dirija-se imediatamente ao hospital 24h mais próximo!',
    timestamp: '09:00',
  },
  {
    id: 'msg-vet-1',
    sender: 'vet',
    vetName: 'Dra. Beatriz Albuquerque',
    vetCrmv: 'CRMV-SP 48.912',
    vetAvatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=200&q=80',
    text: 'Olá, tutor do Thor! Sou a Dra. Beatriz, veterinária de plantão hoje. Já estou com acesso ao prontuário digital do Thor (Golden Retriever, 32.5kg, alérgico a frango e dipirona). Como posso te orientar agora?',
    timestamp: '09:02',
    urgencyLevel: 'low',
  },
];
